fix: Allow re-enabling the camera after both mic and camera are off
garage44/pyrite pull request #113
Opened 2022-08-26 20:32 UTC by emembrives

Before this change, if both the camera and the microphone were turned
off, Pyrite prevented the user from re-enabling their camera.

This change continues to address problems around issue #106.

2022-08-28 06:44 UTC, jvanveen requested changes

2022-08-28 06:44 UTC, jvanveen commented on ui/src/vue/Conference/Groups/Group/Controls.vue
> +            if (should_restart_stream) {
Nice find! Only thing is to keep the variable naming camel case.

2022-08-28 14:36 UTC, emembrives commented on ui/src/vue/Conference/Groups/Group/Controls.vue
> +            if (should_restart_stream) {
Fixed

2022-08-29 09:43 UTC, merged

2022-08-29 09:43 UTC, jvanveen commented
Thanks!